"""Phase 2: Add monitoring models (metrics, anomalies, security_alerts, reports)

Revision ID: bebe13c745a6
Revises: '4c53459a200b'
Create Date: 2025-12-13 21:08:17.207135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bebe13c745a6'
down_revision = '4c53459a200b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_type', sa.Enum('CPU_SPIKE', 'MEMORY_SPIKE', 'NETWORK_SPIKE', 'PORT_OPEN', 'CONNECTION_SURGE', 'LOCK_DETECTED', 'QUERY_SLOW', 'GPU_OVERHEAT', 'UNAUTHORIZED_ACCESS', name='anomaly_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity_level_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.String(length=500), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_table('metric_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('memory_used_mb', sa.Float(), nullable=False),
    sa.Column('memory_total_mb', sa.Float(), nullable=False),
    sa.Column('gpu_percent', sa.Float(), nullable=True),
    sa.Column('gpu_memory_percent', sa.Float(), nullable=True),
    sa.Column('gpu_temperature', sa.Float(), nullable=True),
    sa.Column('network_bytes_sent', sa.Integer(), nullable=False),
    sa.Column('network_bytes_recv', sa.Integer(), nullable=False),
    sa.Column('network_packets_sent', sa.Integer(), nullable=False),
    sa.Column('network_packets_recv', sa.Integer(), nullable=False),
    sa.Column('db_connections_total', sa.Integer(), nullable=False),
    sa.Column('db_connections_active', sa.Integer(), nullable=False),
    sa.Column('db_locks', sa.Integer(), nullable=False),
    sa.Column('db_size_bytes', sa.Integer(), nullable=False),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_samples_sampled_at'), 'metric_samples', ['sampled_at'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity_level_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('local_process', sa.String(length=255), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('is_investigated', sa.Boolean(), nullable=False),
    sa.Column('investigation_notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_detected_at'), 'security_alerts', ['detected_at'], unique=False)
    op.create_table('system_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cpu_avg', sa.Float(), nullable=False),
    sa.Column('cpu_max', sa.Float(), nullable=False),
    sa.Column('cpu_min', sa.Float(), nullable=False),
    sa.Column('memory_avg', sa.Float(), nullable=False),
    sa.Column('memory_max', sa.Float(), nullable=False),
    sa.Column('network_bytes_total', sa.Integer(), nullable=False),
    sa.Column('anomalies_count', sa.Integer(), nullable=False),
    sa.Column('critical_anomalies_count', sa.Integer(), nullable=False),
    sa.Column('security_alerts_count', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('report_files', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_reports_period_start'), 'system_reports', ['period_start'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tenant_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.create_unique_constraint('organizations_name_key', 'organizations', ['name'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.create_index('idx_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_system_reports_period_start'), table_name='system_reports')
    op.drop_table('system_reports')
    op.drop_index(op.f('ix_security_alerts_detected_at'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_metric_samples_sampled_at'), table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
