"""Add ITIL incident management tables

Revision ID: f4b14459abb7
Revises: 'f6bf220e05ab'
Create Date: 2025-12-16 17:54:57.984593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b14459abb7'
down_revision = 'f6bf220e05ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('HARDWARE', 'SOFTWARE', 'NETWORK', 'SECURITY', 'ACCESS', 'PERFORMANCE', 'DATA', 'OTHER', name='incidentcategoryenum'), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', 'P4', name='incidentpriorityenum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incidentstatusenum'), nullable=False),
    sa.Column('impact', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='impactenum'), nullable=False),
    sa.Column('urgency', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='urgencyenum'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('detection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_response_target', sa.Integer(), nullable=True),
    sa.Column('sla_resolution_target', sa.Integer(), nullable=True),
    sa.Column('affected_service', sa.String(length=255), nullable=True),
    sa.Column('affected_users', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('post_mortem', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('incident_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_attachments_id'), 'incident_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_incident_attachments_incident_id'), 'incident_attachments', ['incident_id'], unique=False)
    op.create_table('incident_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_audit_logs_id'), 'incident_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_incident_audit_logs_incident_id'), 'incident_audit_logs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_audit_logs_timestamp'), 'incident_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_audit_logs_timestamp'), table_name='incident_audit_logs')
    op.drop_index(op.f('ix_incident_audit_logs_incident_id'), table_name='incident_audit_logs')
    op.drop_index(op.f('ix_incident_audit_logs_id'), table_name='incident_audit_logs')
    op.drop_table('incident_audit_logs')
    op.drop_index(op.f('ix_incident_attachments_incident_id'), table_name='incident_attachments')
    op.drop_index(op.f('ix_incident_attachments_id'), table_name='incident_attachments')
    op.drop_table('incident_attachments')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
