apiVersion: v1
kind: Secret
metadata:
  name: sentinel-secrets
  namespace: sentinel-system
type: Opaque
data:
  # 'sentinel_default_secure_pass'
  POSTGRES_PASSWORD: c2VudGluZWxfZGVmYXVsdF9zZWN1cmVfcGFzcw==
  # 'sentinel_jwt_secret_change_me'
  JWT_SECRET: c2VudGluZWxfand0X3NlY3JldF9jaGFuZ2VfbWU=
