version: '3.7'

services:
  searxng:
    container_name: sentinel-search-engine
    image: searxng/searxng:latest
    networks:
      - sentinel-net
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=sentinel_search_super_secret_key
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

networks:
  sentinel-net:
    driver: bridge
    internal: false # Necesitamos acceso a internet para buscar, pero lo filtraremos vía iptables/eBPF
