use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0" # Bind to all inside container
  secret_key: "sentinel_search_super_secret_key"
  limiter: false # Deshabilitado para uso interno de SemSH
  image_proxy: true

search:
  safe_search: 2 # Strict
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: bing
    engine: bing
    shortcut: b

ui:
  static_use_hash: true
  query_in_title: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker DB'
